apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n5tvgd8m5-java-quarkus
  janus-idp.io/tekton: n5tvgd8m5-java-quarkus
  backstage.io/kubernetes-id: n5tvgd8m5-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n5tvgd8m5-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
